### ISSUE TITLE
tentacle_pi quit working

### ISSUE THREAD

**Issue by codypower12** [lexruee/tentacle_pi#15]
Had previously used it and worked great put clean SD card in pi was going to reload tentacle_pi and did and this time the bmp180 and am2315 code didnt work anymore. looking for the code for a project could you help a fellow out?

**Comment by justgiterdone** [comment]
I also was unable to complete the install via pip as described on the blog. 
tentacle_pi/am2315/src/am2315_ext.c:9:20: fatal error: Python.h: No such file or directory

compilation terminated.

error: command 'gcc' failed with exit status 1

----------------------------------------
Command /usr/bin/python -c "import setuptools;__file__='/home/pi/build/tentacle-pi/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-c0H2k2-record/install-record.txt failed with error code 1 in /home/pi/build/tentacle-pi
Storing complete log in /root/.pip/pip.log

**Comment by rareed13** [comment]
I'm having the same problem with all of the sensors am2315, bmp180, and the tsl2561. It looks to me that the python coded has been removed from the repository.
